In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/campeonato-brasileiro-full.csv")
df.columns

df.head()

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado
0,1,1,29/03/2003,16:00,Guarani,Vasco,NaN,NaN,NaN,NaN,Guarani,Brinco de Ouro,4,2,SP,RJ
1,2,1,29/03/2003,16:00,Athletico-PR,Gremio,NaN,NaN,NaN,NaN,Athletico-PR,Arena da Baixada,2,0,PR,RS
2,3,1,30/03/2003,16:00,Flamengo,Coritiba,NaN,NaN,NaN,NaN,-,Maracanã,1,1,RJ,PR
3,4,1,30/03/2003,16:00,Goias,Paysandu,NaN,NaN,NaN,NaN,-,Serra Dourada,2,2,GO,PA
4,5,1,30/03/2003,16:00,Internacional,Ponte Preta,NaN,NaN,NaN,NaN,-,Beira Rio,1,1,RS,SP

In [2]:
import pandas as pd

df = pd.read_csv("../data/raw/campeonato-brasileiro-full.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8785 entries, 0 to 8784
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  8785 non-null   int64
 1   rodata              8785 non-null   int64
 2   data                8785 non-null   str
 3   hora                8785 non-null   str
 4   mandante            8785 non-null   str
 5   visitante           8785 non-null   str
 6   formacao_mandante   3810 non-null   str
 7   formacao_visitante  3810 non-null   str
 8   tecnico_mandante    4175 non-null   str
 9   tecnico_visitante   4175 non-null   str
 10  vencedor            8785 non-null   str
 11  arena               8785 non-null   str
 12  mandante_Placar     8785 non-null   int64
 13  visitante_Placar    8785 non-null   int64
 14  mandante_Estado     8785 non-null   str
 15  visitante_Estado    8785 non-null   str
dtypes: int64(4), str(12)
memory usage: 1.1 MB

In [3]:
import pandas as pd

df = pd.read_csv("../data/raw/campeonato-brasileiro-full.csv")
datas = pd.to_datetime(
    df["data"],
    format="%d/%m/%Y"
)

In [4]:
datas.dtype

datas.min(), datas.max()

(Timestamp('2003-03-29 00:00:00'), Timestamp('2024-12-08 00:00:00'))

In [5]:
datas.dt.year.value_counts().sort_index()

data
2003    552
2004    552
2005    462
2006    380
2007    380
2008    380
2009    380
2010    380
2011    380
2012    380
2013    380
2014    380
2015    380
2016    379
2017    380
2018    380
2019    380
2020    268
2021    492
2022    380
2023    380
2024    380
Name: count, dtype: int64

In [6]:
df_2021 = df[datas.dt.year == 2021]

In [7]:
df_2021[["data", "rodata", "mandante", "visitante"]].head(15)

            data  rodata       mandante      visitante
7153  06/01/2021      28         Gremio          Bahia
7154  06/01/2021      28    Botafogo-RJ   Athletico-PR
7155  06/01/2021      28          Sport      Fortaleza
7156  06/01/2021      28       Coritiba          Goias
7157  06/01/2021      28       Flamengo     Fluminense
7158  06/01/2021      28     Bragantino      Sao Paulo
7159  07/01/2021      28          Ceara  Internacional
7160  07/01/2021      28    Atletico-GO          Vasco
7161  09/01/2021      29       Coritiba   Athletico-PR
7162  09/01/2021      29          Sport      Palmeiras
7163  09/01/2021      29      Fortaleza         Gremio
7164  10/01/2021      29      Sao Paulo         Santos
7165  10/01/2021      29       Flamengo          Ceara
7166  10/01/2021      29    Atletico-GO          Bahia
7167  10/01/2021      29  Internacional          Goias

In [8]:
df_2021[df_2021["rodata"] == 1][
    ["data", "rodata", "mandante", "visitante"]
].head(10)

            data  rodata      mandante    visitante
7201  26/01/2021       1     Palmeiras        Vasco
7265  29/05/2021       1        Cuiaba    Juventude
7266  29/05/2021       1         Bahia       Santos
7267  29/05/2021       1     Sao Paulo   Fluminense
7268  30/05/2021       1   Atletico-MG    Fortaleza
7269  30/05/2021       1         Ceara       Gremio
7270  30/05/2021       1      Flamengo    Palmeiras
7271  30/05/2021       1   Chapecoense   Bragantino
7272  30/05/2021       1   Corinthians  Atletico-GO
7273  30/05/2021       1  Athletico-PR   America-MG

In [9]:
df_2021[
    df_2021["rodata"] >= 30
][["data", "rodata", "mandante", "visitante"]].tail(20)

            data  rodata       mandante      visitante
7625  05/12/2021      37          Bahia     Fluminense
7626  05/12/2021      37    Atletico-MG     Bragantino
7627  05/12/2021      37    Corinthians         Gremio
7628  05/12/2021      37          Ceara     America-MG
7629  06/12/2021      37   Athletico-PR      Palmeiras
7630  06/12/2021      37      Sao Paulo      Juventude
7631  06/12/2021      37         Cuiaba      Fortaleza
7632  06/12/2021      37  Internacional    Atletico-GO
7633  06/12/2021      37       Flamengo         Santos
7634  06/12/2021      37    Chapecoense          Sport
7635  09/12/2021      38          Sport   Athletico-PR
7636  09/12/2021      38      Fortaleza          Bahia
7637  09/12/2021      38    Atletico-GO       Flamengo
7638  09/12/2021      38      Palmeiras          Ceara
7639  09/12/2021      38     Fluminense    Chapecoense
7640  09/12/2021      38     America-MG      Sao Paulo
7641  09/12/2021      38     Bragantino  Internacional
7642  09/12/2021      38      Juventude    Corinthians
7643  09/12/2021      38         Gremio    Atletico-MG
7644  09/12/2021      38         Santos         Cuiaba

In [10]:
datas[datas.dt.year == 2021].dt.month.value_counts().sort_index()

data
1     59
2     53
5     10
6     63
7     57
8     47
9     37
10    71
11    69
12    26
Name: count, dtype: int64

In [11]:
datas[
    (datas.dt.year == 2021) &
    (datas.dt.month <= 2)
].max()

Timestamp('2021-02-25 00:00:00')

In [12]:
datas[
    (datas.dt.year == 2021) &
    (datas.dt.month >= 5)
].min()

Timestamp('2021-05-29 00:00:00')

In [13]:
df_work = df.copy()

In [14]:
df_work["data"] = pd.to_datetime(
    df_work["data"],
    format="%d/%m/%Y"
)

In [15]:
df_work["data"].dtype

dtype('<M8[us]')

In [16]:
df_work["temporada"] = df_work["data"].dt.year

In [17]:
jogos_2020_em_2021 = (
    (df_work["data"] >= "2021-01-01") &
    (df_work["data"] <= "2021-02-25")
)

In [18]:
df_work.loc[jogos_2020_em_2021, "temporada"] = 2020

In [19]:
df_work["temporada"].value_counts().sort_index()

temporada
2003    552
2004    552
2005    462
2006    380
2007    380
2008    380
2009    380
2010    380
2011    380
2012    380
2013    380
2014    380
2015    380
2016    379
2017    380
2018    380
2019    380
2020    380
2021    380
2022    380
2023    380
2024    380
Name: count, dtype: int64

In [20]:
df_work.duplicated().sum()

np.int64(0)

In [21]:
df_work.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
8780    False
8781    False
8782    False
8783    False
8784    False
Length: 8785, dtype: bool

In [22]:
df_work.duplicated(
    subset=["temporada", "rodata", "mandante", "visitante"]
).sum()

np.int64(0)

In [23]:
df_work.isna().sum()

ID                       0
rodata                   0
data                     0
hora                     0
mandante                 0
visitante                0
formacao_mandante     4975
formacao_visitante    4975
tecnico_mandante      4610
tecnico_visitante     4610
vencedor                 0
arena                    0
mandante_Placar          0
visitante_Placar         0
mandante_Estado          0
visitante_Estado         0
temporada                0
dtype: int64

In [24]:
(df_work.isna().mean() * 100).round(2)

ID                     0.00
rodata                 0.00
data                   0.00
hora                   0.00
mandante               0.00
visitante              0.00
formacao_mandante     56.63
formacao_visitante    56.63
tecnico_mandante      52.48
tecnico_visitante     52.48
vencedor               0.00
arena                  0.00
mandante_Placar        0.00
visitante_Placar       0.00
mandante_Estado        0.00
visitante_Estado       0.00
temporada              0.00
dtype: float64

In [25]:
df_work["vencedor"].value_counts()

vencedor
-                  2322
Sao Paulo           382
Flamengo            374
Internacional       357
Palmeiras           351
Corinthians         341
Santos              340
Atletico-MG         338
Fluminense          334
Gremio              328
Athletico-PR        320
Cruzeiro            318
Botafogo-RJ         270
Vasco               222
Goias               209
Coritiba            189
Bahia               142
Figueirense         142
Vitoria             136
Sport               131
Fortaleza           127
Ponte Preta         114
Juventude            96
Parana               83
Atletico-GO          79
Ceara                72
Chapecoense          70
Avai                 66
Sao Caetano          65
Bragantino           65
Criciuma             59
America-MG           58
Nautico              54
Paysandu             41
Cuiaba               40
Guarani              36
Portuguesa           31
Santa Cruz           15
Barueri              12
Santo Andre          11
Brasiliense          10
Ipatinga              9
CSA                   8
Gremio Prudente       7
Joinville             7
America-RN            4
Name: count, dtype: int64

In [26]:
empates = df_work[
    df_work["mandante_Placar"] == df_work["visitante_Placar"]
]

In [27]:
empates["vencedor"].value_counts()

vencedor
-    2321
Name: count, dtype: int64

In [28]:
inconsistente = df_work[
    (df_work["vencedor"] == "-") &
    (df_work["mandante_Placar"] != df_work["visitante_Placar"])
]

inconsistente[
    [
        "ID",
        "temporada",
        "rodata",
        "data",
        "mandante",
        "visitante",
        "mandante_Placar",
        "visitante_Placar",
        "vencedor"
    ]
]

,ID,temporada,rodata,data,mandante,visitante,mandante_Placar,visitante_Placar,vencedor
1113,1114,2005,1,2005-04-24,Brasiliense,Vasco,0,1,-

In [29]:
nao_empates = df_work[
    df_work["mandante_Placar"] != df_work["visitante_Placar"]
].copy()

In [30]:
nao_empates["vencedor_pelo_placar"] = nao_empates.apply(
    lambda jogo: jogo["mandante"]
    if jogo["mandante_Placar"] > jogo["visitante_Placar"]
    else jogo["visitante"],
    axis=1
)

In [31]:
nao_empates[
    nao_empates["vencedor"] != nao_empates["vencedor_pelo_placar"]
][
    [
        "temporada",
        "data",
        "mandante",
        "visitante",
        "mandante_Placar",
        "visitante_Placar",
        "vencedor",
        "vencedor_pelo_placar"
    ]
]

,temporada,data,mandante,visitante,mandante_Placar,visitante_Placar,vencedor,vencedor_pelo_placar
1113,2005,2005-04-24,Brasiliense,Vasco,0,1,-,Vasco

In [32]:
df_mvp = df_work[
    df_work["temporada"].between(2020, 2024)
].copy()

In [33]:
df_mvp.shape

(1900, 17)

In [34]:
clubes_2024 = pd.concat([
    df_mvp[df_mvp["temporada"] == 2024]["mandante"],
    df_mvp[df_mvp["temporada"] == 2024]["visitante"]
]).unique()

len(clubes_2024)

20

In [35]:
sorted(clubes_2024)

['Athletico-PR',
 'Atletico-GO',
 'Atletico-MG',
 'Bahia',
 'Botafogo-RJ',
 'Bragantino',
 'Corinthians',
 'Criciuma',
 'Cruzeiro',
 'Cuiaba',
 'Flamengo',
 'Fluminense',
 'Fortaleza',
 'Gremio',
 'Internacional',
 'Juventude',
 'Palmeiras',
 'Sao Paulo',
 'Vasco',
 'Vitoria']

In [36]:
len(clubes_2024)
sorted(clubes_2024)

['Athletico-PR',
 'Atletico-GO',
 'Atletico-MG',
 'Bahia',
 'Botafogo-RJ',
 'Bragantino',
 'Corinthians',
 'Criciuma',
 'Cruzeiro',
 'Cuiaba',
 'Flamengo',
 'Fluminense',
 'Fortaleza',
 'Gremio',
 'Internacional',
 'Juventude',
 'Palmeiras',
 'Sao Paulo',
 'Vasco',
 'Vitoria']

In [37]:
for temporada in sorted(df_mvp["temporada"].unique()):
    jogos_temporada = df_mvp[df_mvp["temporada"] == temporada]

    clubes = pd.concat([
        jogos_temporada["mandante"],
        jogos_temporada["visitante"]
    ]).unique()

    print(temporada, len(clubes))

2020 20
2021 20
2022 20
2023 20
2024 20

In [38]:
for temporada in sorted(df_mvp["temporada"].unique()):
    jogos_temporada = df_mvp[df_mvp["temporada"] == temporada]

    mandantes = jogos_temporada["mandante"].value_counts()
    visitantes = jogos_temporada["visitante"].value_counts()

    print(f"\nTemporada {temporada}")
    print("Mandante:")
    print(mandantes.value_counts())

    print("Visitante:")
    print(visitantes.value_counts())

Temporada 2020
Mandante:
count
19    20
Name: count, dtype: int64
Visitante:
count
19    20
Name: count, dtype: int64

Temporada 2021
Mandante:
count
19    20
Name: count, dtype: int64
Visitante:
count
19    20
Name: count, dtype: int64

Temporada 2022
Mandante:
count
19    20
Name: count, dtype: int64
Visitante:
count
19    20
Name: count, dtype: int64

Temporada 2023
Mandante:
count
19    20
Name: count, dtype: int64
Visitante:
count
19    20
Name: count, dtype: int64

Temporada 2024
Mandante:
count
19    20
Name: count, dtype: int64
Visitante:
count
19    20
Name: count, dtype: int64

In [39]:
jogos_por_rodada = (
    df_mvp
    .groupby(["temporada", "rodata"])
    .size()
)

In [40]:
df_mvp.groupby(["temporada", "rodata"])

In [41]:
jogos_por_rodada.value_counts()

10    190
Name: count, dtype: int64

In [42]:
df_clean = df_mvp[
    [
        "ID",
        "temporada",
        "rodata",
        "data",
        "hora",
        "mandante",
        "visitante",
        "mandante_Placar",
        "visitante_Placar",
        "arena",
        "mandante_Estado",
        "visitante_Estado"
    ]
].copy()

In [43]:
df_clean = df_clean.rename(
    columns={
        "ID": "id",
        "rodata": "rodada",
        "mandante_Placar": "gols_mandante",
        "visitante_Placar": "gols_visitante",
        "mandante_Estado": "estado_mandante",
        "visitante_Estado": "estado_visitante"
    }
)

In [44]:
df_clean.head()
df_clean.info()
df_clean.shape

<class 'pandas.DataFrame'>
RangeIndex: 1900 entries, 6885 to 8784
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                1900 non-null   int64
 1   temporada         1900 non-null   int32
 2   rodada            1900 non-null   int64
 3   data              1900 non-null   datetime64[us]
 4   hora              1900 non-null   str
 5   mandante          1900 non-null   str
 6   visitante         1900 non-null   str
 7   gols_mandante     1900 non-null   int64
 8   gols_visitante    1900 non-null   int64
 9   arena             1900 non-null   str
 10  estado_mandante   1900 non-null   str
 11  estado_visitante  1900 non-null   str
dtypes: datetime64[us](1), int32(1), int64(4), str(6)
memory usage: 170.8 KB

(1900, 12)

In [45]:
df_clean["data_hora"] = pd.to_datetime(
    df_clean["data"].dt.strftime("%Y-%m-%d")
    + " "
    + df_clean["hora"]
)

In [46]:
df_clean[
    ["data", "hora", "data_hora"]
].head()

           data   hora           data_hora
6885 2020-08-08  10:40 2020-08-08 10:40:00
6886 2020-08-08  10:57 2020-08-08 10:57:00
6887 2020-08-08  19:00 2020-08-08 19:00:00
6888 2020-08-09  16:00 2020-08-09 16:00:00
6889 2020-08-09  16:02 2020-08-09 16:02:00

In [47]:
df_clean["data_hora"].isna().sum()

np.int64(0)

In [48]:
df_clean = df_clean.sort_values(
    ["data_hora", "id"]
).reset_index(drop=True)

In [49]:
df_clean[["temporada", "rodada", "data_hora", "mandante", "visitante"]].head(10)

   temporada  rodada           data_hora      mandante      visitante
0       2020       1 2020-08-08 10:40:00         Sport          Ceara
1       2020       1 2020-08-08 10:57:00      Coritiba  Internacional
2       2020       1 2020-08-08 19:00:00     Fortaleza   Athletico-PR
3       2020       1 2020-08-09 16:00:00      Flamengo    Atletico-MG
4       2020       1 2020-08-09 16:02:00        Santos     Bragantino
5       2020       1 2020-08-09 19:00:00        Gremio     Fluminense
6       2020       2 2020-08-12 09:43:00  Athletico-PR          Goias
7       2020       2 2020-08-12 19:15:00    Bragantino    Botafogo-RJ
8       2020       2 2020-08-12 19:16:00   Atletico-MG    Corinthians
9       2020       2 2020-08-12 20:30:00         Bahia       Coritiba

In [50]:
df_clean["resultado"] = "D"

In [51]:
df_clean.loc[
    df_clean["gols_mandante"] > df_clean["gols_visitante"],
    "resultado"
] = "H"

In [52]:
df_clean.loc[
    df_clean["gols_mandante"] < df_clean["gols_visitante"],
    "resultado"
] = "A"

In [53]:
df_clean[
    [
        "mandante",
        "visitante",
        "gols_mandante",
        "gols_visitante",
        "resultado"
    ]
].head(15)

         mandante      visitante  gols_mandante  gols_visitante resultado
0           Sport          Ceara              3               2         H
1        Coritiba  Internacional              0               1         A
2       Fortaleza   Athletico-PR              0               2         A
3        Flamengo    Atletico-MG              0               1         A
4          Santos     Bragantino              1               1         D
5          Gremio     Fluminense              1               0         H
6    Athletico-PR          Goias              2               1         H
7      Bragantino    Botafogo-RJ              1               1         D
8     Atletico-MG    Corinthians              3               2         H
9           Bahia       Coritiba              1               0         H
10    Atletico-GO       Flamengo              3               0         H
11          Ceara         Gremio              1               1         D
12     Fluminense      Palmeiras              1               1         D
13      Sao Paulo      Fortaleza              1               0         H
14  Internacional         Santos              2               0         H

In [54]:
df_clean["resultado"].value_counts()

resultado
H    871
D    528
A    501
Name: count, dtype: int64

In [55]:
(
    df_clean["resultado"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

resultado
H    45.84
D    27.79
A    26.37
Name: proportion, dtype: float64

In [56]:
distribuicao_temporada = pd.crosstab(
    df_clean["temporada"],
    df_clean["resultado"]
)

distribuicao_temporada

resultado    A    D    H
temporada
2020       101  108  171
2021        93  113  174
2022       104  108  168
2023       104   98  178
2024        99  101  180

In [57]:
distribuicao_percentual = pd.crosstab(
    df_clean["temporada"],
    df_clean["resultado"],
    normalize="index"
).mul(100).round(2)

distribuicao_percentual

resultado      A      D      H
temporada
2020       26.58  28.42  45.00
2021       24.47  29.74  45.79
2022       27.37  28.42  44.21
2023       27.37  25.79  46.84
2024       26.05  26.58  47.37

In [58]:
df_work["resultado"] = "D"

df_work.loc[
    df_work["mandante_Placar"] > df_work["visitante_Placar"],
    "resultado"
] = "H"

df_work.loc[
    df_work["mandante_Placar"] < df_work["visitante_Placar"],
    "resultado"
] = "A"

In [59]:
distribuicao_2003_2024 = pd.crosstab(
    df_work["temporada"],
    df_work["resultado"],
    normalize="index"
).mul(100).round(2)

distribuicao_2003_2024

resultado      A      D      H
temporada
2003       20.47  25.72  53.80
2004       22.46  25.36  52.17
2005       27.06  22.08  50.87
2006       24.21  25.53  50.26
2007       25.79  23.68  50.53
2008       20.00  25.26  54.74
2009       21.84  26.84  51.32
2010       21.84  31.05  47.11
2011       23.95  27.63  48.42
2012       24.21  27.63  48.16
2013       23.16  28.42  48.42
2014       23.95  24.21  51.84
2015       23.42  23.95  52.63
2016       21.90  24.80  53.30
2017       28.95  27.11  43.95
2018       17.89  28.95  53.16
2019       25.79  25.79  48.42
2020       26.58  28.42  45.00
2021       24.47  29.74  45.79
2022       27.37  28.42  44.21
2023       27.37  25.79  46.84
2024       26.05  26.58  47.37

In [60]:
df_clean[
    ["gols_mandante", "gols_visitante"]
].mean()

gols_mandante     1.383158
gols_visitante    1.020000
dtype: float64

In [61]:
(
    df_clean["gols_mandante"]
    + df_clean["gols_visitante"]
).mean()

np.float64(2.403157894736842)

In [62]:
media_gols_temporada = (
    df_clean
    .groupby("temporada")[["gols_mandante", "gols_visitante"]]
    .mean()
    .round(3)
)

media_gols_temporada

           gols_mandante  gols_visitante
temporada
2020               1.411           1.074
2021               1.271           0.945
2022               1.405           0.976
2023               1.418           1.071
2024               1.411           1.034

In [63]:
df_clean.shape

(1900, 14)

In [66]:
df_2024 = df_clean[
    df_clean["temporada"] == 2024
].copy()

In [67]:
df_2024["pontos_mandante"] = 0
df_2024["pontos_visitante"] = 0

In [68]:
df_2024.loc[
    df_2024["resultado"] == "H",
    "pontos_mandante"
] = 3

In [69]:
df_2024.loc[
    df_2024["resultado"] == "A",
    "pontos_visitante"
] = 3

In [70]:
df_2024.loc[
    df_2024["resultado"] == "D",
    ["pontos_mandante", "pontos_visitante"]
] = 1

In [71]:
df_2024[
    [
        "mandante",
        "visitante",
        "resultado",
        "pontos_mandante",
        "pontos_visitante"
    ]
].head(10)

           mandante    visitante resultado  pontos_mandante  pontos_visitante
1520  Internacional        Bahia         H                3                 0
1521       Criciuma    Juventude         D                1                 1
1522     Fluminense   Bragantino         D                1                 1
1523      Sao Paulo    Fortaleza         A                0                 3
1524   Athletico-PR       Cuiaba         H                3                 0
1525          Vasco       Gremio         H                3                 0
1526    Atletico-GO     Flamengo         A                0                 3
1527    Corinthians  Atletico-MG         D                1                 1
1528       Cruzeiro  Botafogo-RJ         H                3                 0
1529        Vitoria    Palmeiras         A                0                 3

In [73]:
pontos_casa = (
    df_2024
    .groupby("mandante")["pontos_mandante"]
    .sum()
)

In [75]:
pontos_fora = (
    df_2024
    .groupby("visitante")["pontos_visitante"]
    .sum()
)

In [76]:
tabela_2024 = pd.DataFrame({
    "pontos_casa": pontos_casa,
    "pontos_fora": pontos_fora
})

In [77]:
tabela_2024["pontos"] = (
    tabela_2024["pontos_casa"]
    + tabela_2024["pontos_fora"]
)

In [78]:
tabela_2024.sort_values(
    "pontos",
    ascending=False
)

               pontos_casa  pontos_fora  pontos
Botafogo-RJ             41           38      79
Palmeiras               38           35      73
Flamengo                38           32      70
Fortaleza               47           21      68
Internacional           38           27      65
Sao Paulo               39           20      59
Corinthians             38           18      56
Bahia                   36           17      53
Cruzeiro                35           17      52
Vasco                   35           15      50
Atletico-MG             28           19      47
Vitoria                 27           20      47
Fluminense              29           17      46
Juventude               30           15      45
Gremio                  29           16      45
Bragantino              31           13      44
Athletico-PR            25           17      42
Criciuma                23           15      38
Atletico-GO             20           10      30
Cuiaba                  14           16      30

In [79]:
vitorias_casa = (
    df_2024[df_2024["resultado"] == "H"]
    ["mandante"]
    .value_counts()
)

In [80]:
vitorias_fora = (
    df_2024[df_2024["resultado"] == "A"]
    ["visitante"]
    .value_counts()
)

In [81]:
tabela_2024["vitorias"] = (
    vitorias_casa.add(vitorias_fora, fill_value=0)
)

In [82]:
empates_casa = (
    df_2024[df_2024["resultado"] == "D"]
    ["mandante"]
    .value_counts()
)

empates_fora = (
    df_2024[df_2024["resultado"] == "D"]
    ["visitante"]
    .value_counts()
)

In [83]:
tabela_2024["empates"] = (
    empates_casa.add(empates_fora, fill_value=0)
)

In [84]:
derrotas_casa = (
    df_2024[df_2024["resultado"] == "A"]
    ["mandante"]
    .value_counts()
)

In [86]:
derrotas_fora = (
    df_2024[df_2024["resultado"] == "H"]
    ["visitante"]
    .value_counts()
)

In [87]:
tabela_2024["derrotas"] = (
    derrotas_casa.add(derrotas_fora, fill_value=0)
)

In [88]:
tabela_2024["jogos"] = (
    tabela_2024["vitorias"]
    + tabela_2024["empates"]
    + tabela_2024["derrotas"]
)

In [89]:
tabela_2024[
    ["pontos", "jogos", "vitorias", "empates", "derrotas"]
].sort_values("pontos", ascending=False)

               pontos  jogos  vitorias  empates  derrotas
Botafogo-RJ        79   38.0        23       10       5.0
Palmeiras          73   38.0        22        7       9.0
Flamengo           70   38.0        20       10       8.0
Fortaleza          68   38.0        19       11       8.0
Internacional      65   38.0        18       11       9.0
Sao Paulo          59   38.0        17        8      13.0
Corinthians        56   38.0        15       11      12.0
Bahia              53   38.0        15        8      15.0
Cruzeiro           52   38.0        14       10      14.0
Vasco              50   38.0        14        8      16.0
Atletico-MG        47   38.0        11       14      13.0
Vitoria            47   38.0        13        8      17.0
Fluminense         46   38.0        12       10      16.0
Juventude          45   38.0        11       12      15.0
Gremio             45   38.0        12        9      17.0
Bragantino         44   38.0        10       14      14.0
Athletico-PR       42   38.0        11        9      18.0
Criciuma           38   38.0         9       11      18.0
Atletico-GO        30   38.0         7        9      22.0
Cuiaba             30   38.0         6       12      20.0

In [90]:
gols_pro_casa = (
    df_2024
    .groupby("mandante")["gols_mandante"]
    .sum()
)

In [91]:
gols_pro_fora = (
    df_2024
    .groupby("visitante")["gols_visitante"]
    .sum()
)

In [92]:
tabela_2024["gols_pro"] = (
    gols_pro_casa.add(gols_pro_fora, fill_value=0)
)

In [93]:
df_2024["gols_visitante"]

1520    1
1521    1
1522    2
1523    2
1524    0
       ..
1895    2
1896    1
1897    0
1898    1
1899    3
Name: gols_visitante, Length: 380, dtype: int64

In [94]:
gols_contra_casa = (
    df_2024
    .groupby("mandante")["gols_visitante"]
    .sum()
)

In [95]:
gols_contra_fora = (
    df_2024
    .groupby("visitante")["gols_mandante"]
    .sum()
)

In [96]:
tabela_2024["gols_contra"] = (
    gols_contra_casa.add(gols_contra_fora, fill_value=0)
)

In [97]:
tabela_2024["saldo_gols"] = (
    tabela_2024["gols_pro"]
    - tabela_2024["gols_contra"]
)

In [98]:
tabela_2024[
    [
        "pontos",
        "jogos",
        "vitorias",
        "empates",
        "derrotas",
        "gols_pro",
        "gols_contra",
        "saldo_gols"
    ]
].sort_values(
    ["pontos", "vitorias", "saldo_gols", "gols_pro"],
    ascending=False
)

,pontos,jogos,vitorias,empates,derrotas,gols_pro,gols_contra,saldo_gols
Botafogo-RJ,79,38.0,23,10,5.0,59,29,30
Palmeiras,73,38.0,22,7,9.0,60,33,27
Flamengo,70,38.0,20,10,8.0,61,42,19
Fortaleza,68,38.0,19,11,8.0,53,39,14
Internacional,65,38.0,18,11,9.0,53,36,17
Sao Paulo,59,38.0,17,8,13.0,53,43,10
Corinthians,56,38.0,15,11,12.0,54,45,9
Bahia,53,38.0,15,8,15.0,49,49,0
Cruzeiro,52,38.0,14,10,14.0,43,41,2
Vasco,50,38.0,14,8,16.0,43,56,-13
Vitoria,47,38.0,13,8,17.0,45,52,-7
Atletico-MG,47,38.0,11,14,13.0,47,54,-7
Fluminense,46,38.0,12,10,16.0,33,39,-6
Gremio,45,38.0,12,9,17.0,44,50,-6
Juventude,45,38.0,11,12,15.0,48,59,-11
Bragantino,44,38.0,10,14,14.0,44,48,-4
Athletico-PR,42,38.0,11,9,18.0,40,46,-6
Criciuma,38,38.0,9,11,18.0,42,61,-19
Atletico-GO,30,38.0,7,9,22.0,29,58,-29
Cuiaba,30,38.0,6,12,20.0,29,49,-20

In [99]:
tabela_2024["aproveitamento_casa"] = (
    tabela_2024["pontos_casa"] / 57 * 100
).round(2)

In [100]:
tabela_2024["aproveitamento_fora"] = (
    tabela_2024["pontos_fora"] / 57 * 100
).round(2)

In [101]:
tabela_2024["diferenca_casa_fora"] = (
    tabela_2024["aproveitamento_casa"]
    - tabela_2024["aproveitamento_fora"]
).round(2)

In [102]:
tabela_2024[
    [
        "pontos",
        "pontos_casa",
        "pontos_fora",
        "aproveitamento_casa",
        "aproveitamento_fora",
        "diferenca_casa_fora"
    ]
].sort_values(
    "diferenca_casa_fora",
    ascending=False
)

,pontos,pontos_casa,pontos_fora,aproveitamento_casa,aproveitamento_fora,diferenca_casa_fora
Fortaleza,68,47,21,82.46,36.84,45.62
Corinthians,56,38,18,66.67,31.58,35.09
Vasco,50,35,15,61.40,26.32,35.08
Bahia,53,36,17,63.16,29.82,33.34
Sao Paulo,59,39,20,68.42,35.09,33.33
Cruzeiro,52,35,17,61.40,29.82,31.58
Bragantino,44,31,13,54.39,22.81,31.58
Juventude,45,30,15,52.63,26.32,26.31
Gremio,45,29,16,50.88,28.07,22.81
Fluminense,46,29,17,50.88,29.82,21.06
Internacional,65,38,27,66.67,47.37,19.30
Atletico-GO,30,20,10,35.09,17.54,17.55
Atletico-MG,47,28,19,49.12,33.33,15.79
Athletico-PR,42,25,17,43.86,29.82,14.04
Criciuma,38,23,15,40.35,26.32,14.03
Vitoria,47,27,20,47.37,35.09,12.28
Flamengo,70,38,32,66.67,56.14,10.53
Palmeiras,73,38,35,66.67,61.40,5.27
Botafogo-RJ,79,41,38,71.93,66.67,5.26
Cuiaba,30,14,16,24.56,28.07,-3.51

In [103]:
jogos_mandante = df_clean[
    [
        "id",
        "temporada",
        "rodada",
        "data",
        "mandante",
        "visitante",
        "gols_mandante",
        "gols_visitante",
        "resultado"
    ]
].copy()